### PR TITLE
Support for LiveRamp ATS

### PR DESCRIPTION
**Pull request by pm-shashank-jain**
Refactoring of IdentityHub js files.

### CODE REVIEW

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 18
           

Complexity increasing per file
==============================
- src_new/controllers/idhub.js  6
- test/controllers/idhub.spec.js  1
         

Complexity decreasing per file
==============================
+ src_new/controllers/gpt.js  -4
         

Clones removed
==============
+ src_new/controllers/gpt.js  -7
+ src_new/conf.js  -14
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=12942&bid=44649)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- test/controllers/idhub.spec.js  1
- src_new/controllers/idhub.js  6
         

Complexity decreasing per file
==============================
+ src_new/controllers/gpt.js  -4
         

Clones removed
==============
+ src_new/conf.js  -14
+ src_new/controllers/gpt.js  -7
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=12942&bid=44649)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/controllers/idhub.spec.js  1
- src_new/controllers/idhub.js  6
         

Complexity decreasing per file
==============================
+ src_new/controllers/gpt.js  -2
         

Clones added
============
- src_new/adapters/prebid.js  1
- src_new/controllers/idhub.js  2
         

Clones removed
==============
+ src_new/conf.js  -14
+ src_new/controllers/gpt.js  -7
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=12942&bid=44649)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/controllers/idhub.js  6
- test/controllers/idhub.spec.js  1
         

Complexity decreasing per file
==============================
+ src_new/controllers/gpt.js  -2
         

Clones added
============
- src_new/controllers/idhub.js  2
- src_new/adapters/prebid.js  1
         

Clones removed
==============
+ src_new/controllers/gpt.js  -7
+ src_new/conf.js  -14
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=12942&bid=44649)

**Comment by pm-shashank-jain** [comment]
Merged into staged_nightly

**Pull request closed without merging**
