### PR TITLE
Set pwtplt for outstream

### PR DESCRIPTION
**Pull request by pm-shashank-jain**
Changes for logging pwtplt from video to display for outstream video

### CODE REVIEW

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  2
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Comment by pm-prakhar-jain** [comment]
Hi Shashank, 

As discussed, let's create new PR to add these changes to prebid upgrade release branch. We can close this PR.

Thanks,
Prakhar Jain

**Comment by pm-shashank-jain** [comment]
Hi @pm-prakhar-jain, updated the base branch. Please review

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/adapters/prebid.js  2
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=15206&bid=49908)

**Pull request merged**
