### PR TITLE
do not set prebidConfig if its already set by custom controller

### PR DESCRIPTION
**Pull request by pm-manasi-moghe**

### CODE REVIEW

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/controllers/idhub.js  1
         

Clones removed
==============
+ src_new/controllers/custom.js  -1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=14569&bid=48375)

**Comment by pm-shashank-jain** [comment]
Hi @pm-manasi-moghe, can we just use existing flag of identityOnly  and changes in idhub.js only instead of adding flags in gpt.js and custom.js ? 
So if identityOnly is enabled then only setConfig for userId in idhub.js

**Review by pm-shashank-jain — CHANGES_REQUESTED** [review]
Please make the necessary changes

**Comment by pm-manasi-moghe** [comment]
The function initIdHub gets called from 2 places:
1) init() in idHub.js
2) init() in custom,js

The flag is set from custom.js, to ensure that the prebidConfig doesnt get set twice. 
When initIdHub gets called from idHub,js, the behaviour remains unchanged with the current changes.

**Comment by sureshghare** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src_new/controllers/idhub.js  1
         
```


See the complete overview on [Codacy](https://codacy.pubmatic.com:443/manual/dattaprasad.mundada/OpenWrap/pullRequest?prid=14569&bid=48375)

**Pull request closed without merging**
